/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AdmissionProcessRouteImport } from './routes/admission-process'
import { Route as ArtCraftRouteImport } from './routes/art-craft'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as ChairmanRouteImport } from './routes/chairman'
import { Route as ClassroomsLabsRouteImport } from './routes/classrooms-labs'
import { Route as ComputerLabRouteImport } from './routes/computer-lab'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DanceActivityRoomRouteImport } from './routes/dance-activity-room'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as EventsActivitiesRouteImport } from './routes/events-activities'
import { Route as ExtraCurriculumRouteImport } from './routes/extra-curriculum'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FeeStructureRouteImport } from './routes/fee-structure'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MandatoryDetailsRouteImport } from './routes/mandatory-details'
import { Route as MathematicsLabRouteImport } from './routes/mathematics-lab'
import { Route as MusicDanceRouteImport } from './routes/music-dance'
import { Route as MusicRoomRouteImport } from './routes/music-room'
import { Route as OurAimRouteImport } from './routes/our-aim'
import { Route as OurSchoolRouteImport } from './routes/our-school'
import { Route as PlayRoomRouteImport } from './routes/play-room'
import { Route as PrincipalRouteImport } from './routes/principal'
import { Route as ProspectusRouteImport } from './routes/prospectus'
import { Route as SafetyCareRouteImport } from './routes/safety-care'
import { Route as ScienceLabsRouteImport } from './routes/science-labs'
import { Route as SmartClassesRouteImport } from './routes/smart-classes'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as TransportationRouteImport } from './routes/transportation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionProcessRoute = AdmissionProcessRouteImport.update({
  id: '/admission-process',
  path: '/admission-process',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtCraftRoute = ArtCraftRouteImport.update({
  id: '/art-craft',
  path: '/art-craft',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmanRoute = ChairmanRouteImport.update({
  id: '/chairman',
  path: '/chairman',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsLabsRoute = ClassroomsLabsRouteImport.update({
  id: '/classrooms-labs',
  path: '/classrooms-labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerLabRoute = ComputerLabRouteImport.update({
  id: '/computer-lab',
  path: '/computer-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DanceActivityRoomRoute = DanceActivityRoomRouteImport.update({
  id: '/dance-activity-room',
  path: '/dance-activity-room',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsActivitiesRoute = EventsActivitiesRouteImport.update({
  id: '/events-activities',
  path: '/events-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtraCurriculumRoute = ExtraCurriculumRouteImport.update({
  id: '/extra-curriculum',
  path: '/extra-curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeStructureRoute = FeeStructureRouteImport.update({
  id: '/fee-structure',
  path: '/fee-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MandatoryDetailsRoute = MandatoryDetailsRouteImport.update({
  id: '/mandatory-details',
  path: '/mandatory-details',
  getParentRoute: () => rootRouteImport,
} as any)
const MathematicsLabRoute = MathematicsLabRouteImport.update({
  id: '/mathematics-lab',
  path: '/mathematics-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicDanceRoute = MusicDanceRouteImport.update({
  id: '/music-dance',
  path: '/music-dance',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoomRoute = MusicRoomRouteImport.update({
  id: '/music-room',
  path: '/music-room',
  getParentRoute: () => rootRouteImport,
} as any)
const OurAimRoute = OurAimRouteImport.update({
  id: '/our-aim',
  path: '/our-aim',
  getParentRoute: () => rootRouteImport,
} as any)
const OurSchoolRoute = OurSchoolRouteImport.update({
  id: '/our-school',
  path: '/our-school',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomRoute = PlayRoomRouteImport.update({
  id: '/play-room',
  path: '/play-room',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalRoute = PrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectusRoute = ProspectusRouteImport.update({
  id: '/prospectus',
  path: '/prospectus',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyCareRoute = SafetyCareRouteImport.update({
  id: '/safety-care',
  path: '/safety-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceLabsRoute = ScienceLabsRouteImport.update({
  id: '/science-labs',
  path: '/science-labs',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartClassesRoute = SmartClassesRouteImport.update({
  id: '/smart-classes',
  path: '/smart-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportationRoute = TransportationRouteImport.update({
  id: '/transportation',
  path: '/transportation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/activities': typeof ActivitiesRoute
  '/admission': typeof AdmissionRoute
  '/admission-process': typeof AdmissionProcessRoute
  '/art-craft': typeof ArtCraftRoute
  '/campus': typeof CampusRoute
  '/chairman': typeof ChairmanRoute
  '/classrooms-labs': typeof ClassroomsLabsRoute
  '/computer-lab': typeof ComputerLabRoute
  '/contact': typeof ContactRoute
  '/dance-activity-room': typeof DanceActivityRoomRoute
  '/director': typeof DirectorRoute
  '/events-activities': typeof EventsActivitiesRoute
  '/extra-curriculum': typeof ExtraCurriculumRoute
  '/facilities': typeof FacilitiesRoute
  '/fee-structure': typeof FeeStructureRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/mandatory-details': typeof MandatoryDetailsRoute
  '/mathematics-lab': typeof MathematicsLabRoute
  '/music-dance': typeof MusicDanceRoute
  '/music-room': typeof MusicRoomRoute
  '/our-aim': typeof OurAimRoute
  '/our-school': typeof OurSchoolRoute
  '/play-room': typeof PlayRoomRoute
  '/principal': typeof PrincipalRoute
  '/prospectus': typeof ProspectusRoute
  '/safety-care': typeof SafetyCareRoute
  '/science-labs': typeof ScienceLabsRoute
  '/smart-classes': typeof SmartClassesRoute
  '/sports': typeof SportsRoute
  '/transportation': typeof TransportationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/activities': typeof ActivitiesRoute
  '/admission': typeof AdmissionRoute
  '/admission-process': typeof AdmissionProcessRoute
  '/art-craft': typeof ArtCraftRoute
  '/campus': typeof CampusRoute
  '/chairman': typeof ChairmanRoute
  '/classrooms-labs': typeof ClassroomsLabsRoute
  '/computer-lab': typeof ComputerLabRoute
  '/contact': typeof ContactRoute
  '/dance-activity-room': typeof DanceActivityRoomRoute
  '/director': typeof DirectorRoute
  '/events-activities': typeof EventsActivitiesRoute
  '/extra-curriculum': typeof ExtraCurriculumRoute
  '/facilities': typeof FacilitiesRoute
  '/fee-structure': typeof FeeStructureRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/mandatory-details': typeof MandatoryDetailsRoute
  '/mathematics-lab': typeof MathematicsLabRoute
  '/music-dance': typeof MusicDanceRoute
  '/music-room': typeof MusicRoomRoute
  '/our-aim': typeof OurAimRoute
  '/our-school': typeof OurSchoolRoute
  '/play-room': typeof PlayRoomRoute
  '/principal': typeof PrincipalRoute
  '/prospectus': typeof ProspectusRoute
  '/safety-care': typeof SafetyCareRoute
  '/science-labs': typeof ScienceLabsRoute
  '/smart-classes': typeof SmartClassesRoute
  '/sports': typeof SportsRoute
  '/transportation': typeof TransportationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/activities': typeof ActivitiesRoute
  '/admission': typeof AdmissionRoute
  '/admission-process': typeof AdmissionProcessRoute
  '/art-craft': typeof ArtCraftRoute
  '/campus': typeof CampusRoute
  '/chairman': typeof ChairmanRoute
  '/classrooms-labs': typeof ClassroomsLabsRoute
  '/computer-lab': typeof ComputerLabRoute
  '/contact': typeof ContactRoute
  '/dance-activity-room': typeof DanceActivityRoomRoute
  '/director': typeof DirectorRoute
  '/events-activities': typeof EventsActivitiesRoute
  '/extra-curriculum': typeof ExtraCurriculumRoute
  '/facilities': typeof FacilitiesRoute
  '/fee-structure': typeof FeeStructureRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/mandatory-details': typeof MandatoryDetailsRoute
  '/mathematics-lab': typeof MathematicsLabRoute
  '/music-dance': typeof MusicDanceRoute
  '/music-room': typeof MusicRoomRoute
  '/our-aim': typeof OurAimRoute
  '/our-school': typeof OurSchoolRoute
  '/play-room': typeof PlayRoomRoute
  '/principal': typeof PrincipalRoute
  '/prospectus': typeof ProspectusRoute
  '/safety-care': typeof SafetyCareRoute
  '/science-labs': typeof ScienceLabsRoute
  '/smart-classes': typeof SmartClassesRoute
  '/sports': typeof SportsRoute
  '/transportation': typeof TransportationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/activities'
    | '/admission'
    | '/admission-process'
    | '/art-craft'
    | '/campus'
    | '/chairman'
    | '/classrooms-labs'
    | '/computer-lab'
    | '/contact'
    | '/dance-activity-room'
    | '/director'
    | '/events-activities'
    | '/extra-curriculum'
    | '/facilities'
    | '/fee-structure'
    | '/gallery'
    | '/library'
    | '/mandatory-details'
    | '/mathematics-lab'
    | '/music-dance'
    | '/music-room'
    | '/our-aim'
    | '/our-school'
    | '/play-room'
    | '/principal'
    | '/prospectus'
    | '/safety-care'
    | '/science-labs'
    | '/smart-classes'
    | '/sports'
    | '/transportation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/activities'
    | '/admission'
    | '/admission-process'
    | '/art-craft'
    | '/campus'
    | '/chairman'
    | '/classrooms-labs'
    | '/computer-lab'
    | '/contact'
    | '/dance-activity-room'
    | '/director'
    | '/events-activities'
    | '/extra-curriculum'
    | '/facilities'
    | '/fee-structure'
    | '/gallery'
    | '/library'
    | '/mandatory-details'
    | '/mathematics-lab'
    | '/music-dance'
    | '/music-room'
    | '/our-aim'
    | '/our-school'
    | '/play-room'
    | '/principal'
    | '/prospectus'
    | '/safety-care'
    | '/science-labs'
    | '/smart-classes'
    | '/sports'
    | '/transportation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/activities'
    | '/admission'
    | '/admission-process'
    | '/art-craft'
    | '/campus'
    | '/chairman'
    | '/classrooms-labs'
    | '/computer-lab'
    | '/contact'
    | '/dance-activity-room'
    | '/director'
    | '/events-activities'
    | '/extra-curriculum'
    | '/facilities'
    | '/fee-structure'
    | '/gallery'
    | '/library'
    | '/mandatory-details'
    | '/mathematics-lab'
    | '/music-dance'
    | '/music-room'
    | '/our-aim'
    | '/our-school'
    | '/play-room'
    | '/principal'
    | '/prospectus'
    | '/safety-care'
    | '/science-labs'
    | '/smart-classes'
    | '/sports'
    | '/transportation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdmissionRoute: typeof AdmissionRoute
  AdmissionProcessRoute: typeof AdmissionProcessRoute
  ArtCraftRoute: typeof ArtCraftRoute
  CampusRoute: typeof CampusRoute
  ChairmanRoute: typeof ChairmanRoute
  ClassroomsLabsRoute: typeof ClassroomsLabsRoute
  ComputerLabRoute: typeof ComputerLabRoute
  ContactRoute: typeof ContactRoute
  DanceActivityRoomRoute: typeof DanceActivityRoomRoute
  DirectorRoute: typeof DirectorRoute
  EventsActivitiesRoute: typeof EventsActivitiesRoute
  ExtraCurriculumRoute: typeof ExtraCurriculumRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FeeStructureRoute: typeof FeeStructureRoute
  GalleryRoute: typeof GalleryRoute
  LibraryRoute: typeof LibraryRoute
  MandatoryDetailsRoute: typeof MandatoryDetailsRoute
  MathematicsLabRoute: typeof MathematicsLabRoute
  MusicDanceRoute: typeof MusicDanceRoute
  MusicRoomRoute: typeof MusicRoomRoute
  OurAimRoute: typeof OurAimRoute
  OurSchoolRoute: typeof OurSchoolRoute
  PlayRoomRoute: typeof PlayRoomRoute
  PrincipalRoute: typeof PrincipalRoute
  ProspectusRoute: typeof ProspectusRoute
  SafetyCareRoute: typeof SafetyCareRoute
  ScienceLabsRoute: typeof ScienceLabsRoute
  SmartClassesRoute: typeof SmartClassesRoute
  SportsRoute: typeof SportsRoute
  TransportationRoute: typeof TransportationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission-process': {
      id: '/admission-process'
      path: '/admission-process'
      fullPath: '/admission-process'
      preLoaderRoute: typeof AdmissionProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art-craft': {
      id: '/art-craft'
      path: '/art-craft'
      fullPath: '/art-craft'
      preLoaderRoute: typeof ArtCraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairman': {
      id: '/chairman'
      path: '/chairman'
      fullPath: '/chairman'
      preLoaderRoute: typeof ChairmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms-labs': {
      id: '/classrooms-labs'
      path: '/classrooms-labs'
      fullPath: '/classrooms-labs'
      preLoaderRoute: typeof ClassroomsLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer-lab': {
      id: '/computer-lab'
      path: '/computer-lab'
      fullPath: '/computer-lab'
      preLoaderRoute: typeof ComputerLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dance-activity-room': {
      id: '/dance-activity-room'
      path: '/dance-activity-room'
      fullPath: '/dance-activity-room'
      preLoaderRoute: typeof DanceActivityRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-activities': {
      id: '/events-activities'
      path: '/events-activities'
      fullPath: '/events-activities'
      preLoaderRoute: typeof EventsActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extra-curriculum': {
      id: '/extra-curriculum'
      path: '/extra-curriculum'
      fullPath: '/extra-curriculum'
      preLoaderRoute: typeof ExtraCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-structure': {
      id: '/fee-structure'
      path: '/fee-structure'
      fullPath: '/fee-structure'
      preLoaderRoute: typeof FeeStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandatory-details': {
      id: '/mandatory-details'
      path: '/mandatory-details'
      fullPath: '/mandatory-details'
      preLoaderRoute: typeof MandatoryDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mathematics-lab': {
      id: '/mathematics-lab'
      path: '/mathematics-lab'
      fullPath: '/mathematics-lab'
      preLoaderRoute: typeof MathematicsLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-dance': {
      id: '/music-dance'
      path: '/music-dance'
      fullPath: '/music-dance'
      preLoaderRoute: typeof MusicDanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-room': {
      id: '/music-room'
      path: '/music-room'
      fullPath: '/music-room'
      preLoaderRoute: typeof MusicRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-aim': {
      id: '/our-aim'
      path: '/our-aim'
      fullPath: '/our-aim'
      preLoaderRoute: typeof OurAimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-school': {
      id: '/our-school'
      path: '/our-school'
      fullPath: '/our-school'
      preLoaderRoute: typeof OurSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-room': {
      id: '/play-room'
      path: '/play-room'
      fullPath: '/play-room'
      preLoaderRoute: typeof PlayRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal': {
      id: '/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof PrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospectus': {
      id: '/prospectus'
      path: '/prospectus'
      fullPath: '/prospectus'
      preLoaderRoute: typeof ProspectusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-care': {
      id: '/safety-care'
      path: '/safety-care'
      fullPath: '/safety-care'
      preLoaderRoute: typeof SafetyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science-labs': {
      id: '/science-labs'
      path: '/science-labs'
      fullPath: '/science-labs'
      preLoaderRoute: typeof ScienceLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-classes': {
      id: '/smart-classes'
      path: '/smart-classes'
      fullPath: '/smart-classes'
      preLoaderRoute: typeof SmartClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportation': {
      id: '/transportation'
      path: '/transportation'
      fullPath: '/transportation'
      preLoaderRoute: typeof TransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdmissionRoute: AdmissionRoute,
  AdmissionProcessRoute: AdmissionProcessRoute,
  ArtCraftRoute: ArtCraftRoute,
  CampusRoute: CampusRoute,
  ChairmanRoute: ChairmanRoute,
  ClassroomsLabsRoute: ClassroomsLabsRoute,
  ComputerLabRoute: ComputerLabRoute,
  ContactRoute: ContactRoute,
  DanceActivityRoomRoute: DanceActivityRoomRoute,
  DirectorRoute: DirectorRoute,
  EventsActivitiesRoute: EventsActivitiesRoute,
  ExtraCurriculumRoute: ExtraCurriculumRoute,
  FacilitiesRoute: FacilitiesRoute,
  FeeStructureRoute: FeeStructureRoute,
  GalleryRoute: GalleryRoute,
  LibraryRoute: LibraryRoute,
  MandatoryDetailsRoute: MandatoryDetailsRoute,
  MathematicsLabRoute: MathematicsLabRoute,
  MusicDanceRoute: MusicDanceRoute,
  MusicRoomRoute: MusicRoomRoute,
  OurAimRoute: OurAimRoute,
  OurSchoolRoute: OurSchoolRoute,
  PlayRoomRoute: PlayRoomRoute,
  PrincipalRoute: PrincipalRoute,
  ProspectusRoute: ProspectusRoute,
  SafetyCareRoute: SafetyCareRoute,
  ScienceLabsRoute: ScienceLabsRoute,
  SmartClassesRoute: SmartClassesRoute,
  SportsRoute: SportsRoute,
  TransportationRoute: TransportationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
